//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumeWebservice.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QuadraticResult", Namespace="http://mywebserviceproject.org/")]
    [System.SerializableAttribute()]
    public partial class QuadraticResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool HasSolutionField;
        
        private System.Nullable<double> Root1Field;
        
        private System.Nullable<double> Root2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool HasSolution {
            get {
                return this.HasSolutionField;
            }
            set {
                if ((this.HasSolutionField.Equals(value) != true)) {
                    this.HasSolutionField = value;
                    this.RaisePropertyChanged("HasSolution");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<double> Root1 {
            get {
                return this.Root1Field;
            }
            set {
                if ((this.Root1Field.Equals(value) != true)) {
                    this.Root1Field = value;
                    this.RaisePropertyChanged("Root1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<double> Root2 {
            get {
                return this.Root2Field;
            }
            set {
                if ((this.Root2Field.Equals(value) != true)) {
                    this.Root2Field = value;
                    this.RaisePropertyChanged("Root2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://mywebserviceproject.org/", ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name name from namespace http://mywebserviceproject.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://mywebserviceproject.org/GreetAssistant", ReplyAction="*")]
        ConsumeWebservice.ServiceReference1.GreetAssistantResponse GreetAssistant(ConsumeWebservice.ServiceReference1.GreetAssistantRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mywebserviceproject.org/GreetAssistant", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumeWebservice.ServiceReference1.GreetAssistantResponse> GreetAssistantAsync(ConsumeWebservice.ServiceReference1.GreetAssistantRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mywebserviceproject.org/FahrenheitToCelsius", ReplyAction="*")]
        double FahrenheitToCelsius(double fahrenheit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mywebserviceproject.org/FahrenheitToCelsius", ReplyAction="*")]
        System.Threading.Tasks.Task<double> FahrenheitToCelsiusAsync(double fahrenheit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mywebserviceproject.org/CelsiusToFahrenheit", ReplyAction="*")]
        double CelsiusToFahrenheit(double celsius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mywebserviceproject.org/CelsiusToFahrenheit", ReplyAction="*")]
        System.Threading.Tasks.Task<double> CelsiusToFahrenheitAsync(double celsius);
        
        // CODEGEN: Generating message contract since element name SolveQuadraticEquationResult from namespace http://mywebserviceproject.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://mywebserviceproject.org/SolveQuadraticEquation", ReplyAction="*")]
        ConsumeWebservice.ServiceReference1.SolveQuadraticEquationResponse SolveQuadraticEquation(ConsumeWebservice.ServiceReference1.SolveQuadraticEquationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mywebserviceproject.org/SolveQuadraticEquation", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumeWebservice.ServiceReference1.SolveQuadraticEquationResponse> SolveQuadraticEquationAsync(ConsumeWebservice.ServiceReference1.SolveQuadraticEquationRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GreetAssistantRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GreetAssistant", Namespace="http://mywebserviceproject.org/", Order=0)]
        public ConsumeWebservice.ServiceReference1.GreetAssistantRequestBody Body;
        
        public GreetAssistantRequest() {
        }
        
        public GreetAssistantRequest(ConsumeWebservice.ServiceReference1.GreetAssistantRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://mywebserviceproject.org/")]
    public partial class GreetAssistantRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public GreetAssistantRequestBody() {
        }
        
        public GreetAssistantRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GreetAssistantResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GreetAssistantResponse", Namespace="http://mywebserviceproject.org/", Order=0)]
        public ConsumeWebservice.ServiceReference1.GreetAssistantResponseBody Body;
        
        public GreetAssistantResponse() {
        }
        
        public GreetAssistantResponse(ConsumeWebservice.ServiceReference1.GreetAssistantResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://mywebserviceproject.org/")]
    public partial class GreetAssistantResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GreetAssistantResult;
        
        public GreetAssistantResponseBody() {
        }
        
        public GreetAssistantResponseBody(string GreetAssistantResult) {
            this.GreetAssistantResult = GreetAssistantResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SolveQuadraticEquationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SolveQuadraticEquation", Namespace="http://mywebserviceproject.org/", Order=0)]
        public ConsumeWebservice.ServiceReference1.SolveQuadraticEquationRequestBody Body;
        
        public SolveQuadraticEquationRequest() {
        }
        
        public SolveQuadraticEquationRequest(ConsumeWebservice.ServiceReference1.SolveQuadraticEquationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://mywebserviceproject.org/")]
    public partial class SolveQuadraticEquationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double a;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double b;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double c;
        
        public SolveQuadraticEquationRequestBody() {
        }
        
        public SolveQuadraticEquationRequestBody(double a, double b, double c) {
            this.a = a;
            this.b = b;
            this.c = c;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SolveQuadraticEquationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SolveQuadraticEquationResponse", Namespace="http://mywebserviceproject.org/", Order=0)]
        public ConsumeWebservice.ServiceReference1.SolveQuadraticEquationResponseBody Body;
        
        public SolveQuadraticEquationResponse() {
        }
        
        public SolveQuadraticEquationResponse(ConsumeWebservice.ServiceReference1.SolveQuadraticEquationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://mywebserviceproject.org/")]
    public partial class SolveQuadraticEquationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsumeWebservice.ServiceReference1.QuadraticResult SolveQuadraticEquationResult;
        
        public SolveQuadraticEquationResponseBody() {
        }
        
        public SolveQuadraticEquationResponseBody(ConsumeWebservice.ServiceReference1.QuadraticResult SolveQuadraticEquationResult) {
            this.SolveQuadraticEquationResult = SolveQuadraticEquationResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : ConsumeWebservice.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<ConsumeWebservice.ServiceReference1.WebService1Soap>, ConsumeWebservice.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumeWebservice.ServiceReference1.GreetAssistantResponse ConsumeWebservice.ServiceReference1.WebService1Soap.GreetAssistant(ConsumeWebservice.ServiceReference1.GreetAssistantRequest request) {
            return base.Channel.GreetAssistant(request);
        }
        
        public string GreetAssistant(string name) {
            ConsumeWebservice.ServiceReference1.GreetAssistantRequest inValue = new ConsumeWebservice.ServiceReference1.GreetAssistantRequest();
            inValue.Body = new ConsumeWebservice.ServiceReference1.GreetAssistantRequestBody();
            inValue.Body.name = name;
            ConsumeWebservice.ServiceReference1.GreetAssistantResponse retVal = ((ConsumeWebservice.ServiceReference1.WebService1Soap)(this)).GreetAssistant(inValue);
            return retVal.Body.GreetAssistantResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumeWebservice.ServiceReference1.GreetAssistantResponse> ConsumeWebservice.ServiceReference1.WebService1Soap.GreetAssistantAsync(ConsumeWebservice.ServiceReference1.GreetAssistantRequest request) {
            return base.Channel.GreetAssistantAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumeWebservice.ServiceReference1.GreetAssistantResponse> GreetAssistantAsync(string name) {
            ConsumeWebservice.ServiceReference1.GreetAssistantRequest inValue = new ConsumeWebservice.ServiceReference1.GreetAssistantRequest();
            inValue.Body = new ConsumeWebservice.ServiceReference1.GreetAssistantRequestBody();
            inValue.Body.name = name;
            return ((ConsumeWebservice.ServiceReference1.WebService1Soap)(this)).GreetAssistantAsync(inValue);
        }
        
        public double FahrenheitToCelsius(double fahrenheit) {
            return base.Channel.FahrenheitToCelsius(fahrenheit);
        }
        
        public System.Threading.Tasks.Task<double> FahrenheitToCelsiusAsync(double fahrenheit) {
            return base.Channel.FahrenheitToCelsiusAsync(fahrenheit);
        }
        
        public double CelsiusToFahrenheit(double celsius) {
            return base.Channel.CelsiusToFahrenheit(celsius);
        }
        
        public System.Threading.Tasks.Task<double> CelsiusToFahrenheitAsync(double celsius) {
            return base.Channel.CelsiusToFahrenheitAsync(celsius);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumeWebservice.ServiceReference1.SolveQuadraticEquationResponse ConsumeWebservice.ServiceReference1.WebService1Soap.SolveQuadraticEquation(ConsumeWebservice.ServiceReference1.SolveQuadraticEquationRequest request) {
            return base.Channel.SolveQuadraticEquation(request);
        }
        
        public ConsumeWebservice.ServiceReference1.QuadraticResult SolveQuadraticEquation(double a, double b, double c) {
            ConsumeWebservice.ServiceReference1.SolveQuadraticEquationRequest inValue = new ConsumeWebservice.ServiceReference1.SolveQuadraticEquationRequest();
            inValue.Body = new ConsumeWebservice.ServiceReference1.SolveQuadraticEquationRequestBody();
            inValue.Body.a = a;
            inValue.Body.b = b;
            inValue.Body.c = c;
            ConsumeWebservice.ServiceReference1.SolveQuadraticEquationResponse retVal = ((ConsumeWebservice.ServiceReference1.WebService1Soap)(this)).SolveQuadraticEquation(inValue);
            return retVal.Body.SolveQuadraticEquationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumeWebservice.ServiceReference1.SolveQuadraticEquationResponse> ConsumeWebservice.ServiceReference1.WebService1Soap.SolveQuadraticEquationAsync(ConsumeWebservice.ServiceReference1.SolveQuadraticEquationRequest request) {
            return base.Channel.SolveQuadraticEquationAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumeWebservice.ServiceReference1.SolveQuadraticEquationResponse> SolveQuadraticEquationAsync(double a, double b, double c) {
            ConsumeWebservice.ServiceReference1.SolveQuadraticEquationRequest inValue = new ConsumeWebservice.ServiceReference1.SolveQuadraticEquationRequest();
            inValue.Body = new ConsumeWebservice.ServiceReference1.SolveQuadraticEquationRequestBody();
            inValue.Body.a = a;
            inValue.Body.b = b;
            inValue.Body.c = c;
            return ((ConsumeWebservice.ServiceReference1.WebService1Soap)(this)).SolveQuadraticEquationAsync(inValue);
        }
    }
}
